.TH "PDD" "1" "Jul 2017" "Version 1.0" "User Commands"
.SH NAME
pdd \- Date, time difference calculator.
.SH SYNOPSIS
.B pdd [OPTIONS]
.SH DESCRIPTION
.B pdd
(python3 date diff) is a small utility to calculate date and time difference. It shows the current date, time and timezone if no program arguments are passed.
.PP
.B Operational notes
.PP
- Month can be specified as month number (e.g. Jan - 1, Dec - 12).
.br
- The absolute difference is shown. Argument order is ignored.
.br
- The end date is excluded in date difference calculations.
.br
- Hour, minute or second can be omitted. Partial inputs are recognized as \fImm:ss\fR or \fIss\fR.
.SH OPTIONS
.TP
.BI "-h, --help"
Show help text and exit.
.TP
.BI "-d" " dd mmm yyyy dd mmm yyyy"
Show the difference between two dates.
.TP
.BI "-t" " hh:mm:ss hh:mm:ss"
Show the difference between two timestamps.
.SH EXAMPLES
.PP
.IP 1. 4
Calculate date diff:
.PP
.EX
.IP
.B $ pdd -d 3 jul 1983 15 1 2014
.EE
.PP
.IP 2. 4
Calculate time diff:
.PP
.EX
.IP
.B $ pdd -t 45:50 6:17:33
.EE
.PP
.IP 3. 4
Show current date, time and timezone:
.PP
.EX
.IP
.B $ pdd
.EE
.PP
.IP 4. 4
Specify time will roll-over:
.PP
.EX
.IP
.B $ pdd -t 5:80:75 6:17:33
.SH AUTHORS
Arun Prakash Jana <engineerarun@gmail.com>
.SH HOME
.I https://github.com/jarun/pdd
.SH REPORTING BUGS
.I https://github.com/jarun/pdd/issues
.SH LICENSE
Copyright \(co 2017 Arun Prakash Jana <engineerarun@gmail.com>
.PP
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
