.TH "PDD" "1" "26 Sep 2017" "Version 1.1" "User Commands"
.SH NAME
pdd \- Tiny date, time difference calculator with timers.
.SH SYNOPSIS
.B pdd [OPTIONS] [KEYWORDS ...]
.SH DESCRIPTION
.B pdd
(python3 date diff) is a small utility to calculate date and time difference. It can also be used as a timer. If no program arguments are specified it shows the current date, time and timezone.
.PP
.B Features
.PP
- calculate date difference
.br
- calculate time difference
.br
- add, subtract duration (timeslice) to/from date (time)
.br
- calculate diff from \fItoday\fR and \fInow\fR
.br
- countdown timer
.br
- millisecond resolution stopwatch
.br
- show current date, time and timezone
.br
- minimal dependencies
.PP
.B Operational notes
.PP
- Time is in 24-hr format.
.br
- Month can be specified as month number (e.g. Jan - 1, Dec - 12).
.br
- The absolute difference is shown. Argument order is ignored.
.br
- The end date is excluded in date difference calculations.
.br
- Hour, minute or second can be omitted. Partial inputs are recognized as \fImm:ss\fR or \fIss\fR.
.SH OPTIONS
.TP
.BI "-h, --help"
Show help text and exit.
.TP
.BI "-d" " dd mmm yyyy [dd mmm yyyy | d m y]"
Calculate date difference.
.TP
.BI "-t" " hh:mm:ss [hh:mm:ss | h:m:s]"
Calculate time difference.
.TP
.BI "--add"
Add a duration or timeslice to date (/today) or time (/now).
.TP
.BI "--sub"
Subtract a duration or timeslice from date (/today) or time (/now).
.TP
.BI "--day" " dd mmm yyyy"
Show the day of the week on a date.
.TP
.BI "-c" " hh:mm:ss"
Set a countdown timer with duration in hours, minutes and seconds.
.TP
.BI "-s"
Start a millisecond resolution stopwatch.
.SH EXAMPLES
.PP
.IP 1. 4
Calculate date diff:
.PP
.EX
.IP
.B $ pdd -d 3 jul 1983 15 1 2014
.EE
.PP
.IP 2. 4
Calculate time diff:
.PP
.EX
.IP
.B $ pdd -t 45:50 6:17:33
.EE
.PP
.IP 3. 4
Show current date, time and timezone:
.PP
.EX
.IP
.B $ pdd
.EE
.PP
.IP 4. 4
Specify time with roll-over:
.PP
.EX
.IP
.B $ pdd -t 5:80:75 6:17:33
.EE
.PP
.IP 5. 4
Calculate diff from \fBtoday\fR:
.PP
.EX
.IP
.B $ pdd 15 Jan 2015
.EE
.PP
.IP 6. 4
Calculate diff from \fBnow\fR:
.PP
.EX
.IP
.B $ pdd 24:00:00
.B $ pdd 0
.EE
.PP
.IP 7. 4
Add a duration (1 day, 2 months, 3 years) to 28 Feb, 2000:
.PP
.EX
.IP
.B $ pdd -d 28 FEB 2000 1 2 3 --add
.EE
.PP
.IP 8. 4
Add a timeslice (1 hour 2 mins 3 secs) to 23:45:37:
.PP
.EX
.IP
.B $ pdd -t 23:45:37 1:2:3 --add
.EE
.PP
.IP 9. 4
Add a duration (1 day, 2 months, 3 years) to \fBtoday\fR:
.PP
.EX
.IP
.B $ pdd 1 2 3 --add
.EE
.PP
.IP 10. 4
Add a timeslice (1 hour 2 minutes 3 seconds) to \fBnow\fR:
.PP
.EX
.IP
.B $ pdd 1:2:3 --add
.EE
.PP
.IP 11. 4
Subtract a duration (1 day) from 1 Mar, 2000:
.PP
.EX
.IP
.B $ pdd -d 01 Mar 2000 1 0 0 --sub
.EE
.PP
.IP 12. 4
Subtract a timeslice (1 sec) from midnight:
.PP
.EX
.IP
.B $ pdd -t 00:00:00 0:0:1 --sub
.EE
.PP
.IP 13. 4
Subtract a duration (1 day, 2 months, 3 years) from \fBtoday\fR:
.PP
.EX
.IP
.B $ pdd 1 2 3 --sub
.EE
.PP
.IP 14. 4
Subtract a timeslice (1 hour 2 minutes 3 seconds) from \fBnow\fR:
.PP
.EX
.IP
.B $ pdd 1:2:3 --sub
.EE
.PP
.IP 15. 4
Show the day of the week on 15 Jan 2014:
.PP
.EX
.IP
.B $ pdd --day 15 Jan 2014
.SH AUTHORS
Arun Prakash Jana <engineerarun@gmail.com>
.SH HOME
.I https://github.com/jarun/pdd
.SH REPORTING BUGS
.I https://github.com/jarun/pdd/issues
.SH LICENSE
Copyright \(co 2017 Arun Prakash Jana <engineerarun@gmail.com>
.PP
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
