version: 2

test-template: &test-template
  working_directory: ~/pdd
  environment:
    CI_FORCE_TEST: 1
  steps:
    - run:
        command: |
          apt update && apt install -y --no-install-recommends git make
          pip install --upgrade setuptools flake8 pylint python-dateutil logilab-common pytest
    - checkout
    - run:
        command: |
          python -m flake8 pdd
          echo pdd | xargs pylint
          make check

jobs:
  py38:
    docker:
      - image: python:3.8-slim
    <<: *test-template

  py39:
    docker:
      - image: python:3.9-slim
    <<: *test-template

  py310:
    docker:
      - image: python:3.10-slim
    <<: *test-template

  py311:
    docker:
      - image: python:3.11-slim
    <<: *test-template

  py312:
    docker:
      - image: python:3.12-slim
    <<: *test-template

#  package-and-publish:
#    machine: true
#    working_directory: ~/pdd
#    steps:
#      - checkout
#      - run:
#          name: "package with packagecore"
#          command: |
#            # Use latest installed python3 from pyenv
#            export PYENV_VERSION="$(pyenv versions | grep -Po '\b3\.\d+\.\d+' | tail -1)"
#            pip install packagecore
#            packagecore -o ./dist/ ${CIRCLE_TAG#v}
#      - run:
#          name: "publish to GitHub"
#          command: |
#            go install github.com/tcnksm/ghr@latest
#            ghr -t ${GITHUB_API_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./dist/

workflows:
  version: 2

  CircleCI:
    jobs: &all-tests
      - py38
      - py39
      - py310
      - py311
      - py312

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * 6"
          filters:
            branches:
              only:
                - master
    jobs: *all-tests

#  publish-github-release:
#    jobs:
#      - package-and-publish:
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/
